import { describe, expect, it } from "vitest";

import {
  buildYtdlpSubtitleArgs,
  parseVttPlainText,
} from "../../../src/social/video-text.js";

describe("video subtitle extraction arguments", () => {
  it("builds yt-dlp subtitle arguments with language and browser-cookie reuse", () => {
    expect(
      buildYtdlpSubtitleArgs({
        url: "https://www.youtube.com/watch?v=abc",
        outputTemplate: "/tmp/unicli/%(id)s.%(ext)s",
        languages: ["zh-Hans", "en"],
        cookiesFromBrowser: "chrome",
      }),
    ).toEqual([
      "--skip-download",
      "--write-sub",
      "--write-auto-sub",
      "--sub-lang",
      "zh-Hans,en",
      "--sub-format",
      "vtt/best",
      "--convert-subs",
      "vtt",
      "--cookies-from-browser",
      "chrome",
      "-o",
      "/tmp/unicli/%(id)s.%(ext)s",
      "https://www.youtube.com/watch?v=abc",
    ]);
  });

  it("rejects empty URLs and empty language lists", () => {
    expect(() =>
      buildYtdlpSubtitleArgs({
        url: "",
        outputTemplate: "/tmp/%(id)s.%(ext)s",
      }),
    ).toThrow("url is required");

    expect(() =>
      buildYtdlpSubtitleArgs({
        url: "https://example.com/video",
        outputTemplate: "/tmp/%(id)s.%(ext)s",
        languages: [],
      }),
    ).toThrow("at least one subtitle language is required");
  });

  it("turns VTT cues into LLM-readable plain text", () => {
    expect(
      parseVttPlainText(`WEBVTT - generated by yt-dlp
Kind: captions
Language: en
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:900000

00:00:00.000 --> 00:00:02.000 align:start position:0%
<v Speaker>Donald Trump spoke today &amp; repeated the phrase.

00:00:02.000 --> 00:00:04.000
Donald Trump spoke today &amp; repeated the phrase.

00:00:04.000 --> 00:00:06.000
The full context matters.
`),
    ).toBe(
      "Donald Trump spoke today & repeated the phrase.\nThe full context matters.",
    );
  });

  it("keeps escaped comparison operators while removing VTT tags", () => {
    expect(
      parseVttPlainText(`WEBVTT

00:00:00.000 --> 00:00:02.000
<c.yellow>Use x &lt; 3 &amp;&amp; y &gt; 1</c>
`),
    ).toBe("Use x < 3 && y > 1");
  });
});
