/** Official CCF seventh-edition A-class conference records, updated 2026-04-09.
 * Source: the formal PDF linked from https://www.ccf.org.cn/Academic_Evaluation/By_category/
 */

export interface CcfConferenceRecord {
  acronym: string;
  aliases: readonly string[];
  name: string;
  category: string;
  publisher: string;
  rank: "A";
  edition: 7;
  directory_year: 2026;
  updated: "2026-04-09";
  official_venue_url: string;
  source_url: string;
  pdf_page: number;
}

export const CCF_A_CONFERENCES: readonly CcfConferenceRecord[] = [
  {
    acronym: "PPoPP",
    aliases: [],
    name: "ACM SIGPLAN Symposium on Principles & Practice of Parallel Programming",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/ppopp/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "FAST",
    aliases: [],
    name: "USENIX Conference on File and Storage Technologies",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "USENIX",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/fast/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "DAC",
    aliases: [],
    name: "Design Automation Conference",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "https://dblp.uni-trier.de/db/conf/dac/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "HPCA",
    aliases: [],
    name: "IEEE International Symposium on High Performance Computer Architecture",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/hpca/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "MICRO",
    aliases: [],
    name: "IEEE/ACM International Symposium on Microarchitecture",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "IEEE/ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "https://dblp.uni-trier.de/db/conf/micro/index.html",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "SC",
    aliases: [],
    name: "International Conference for High Performance Computing, Networking, Storage, and Analysis",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/sc/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "ASPLOS",
    aliases: [],
    name: "International Conference on Architectural Support for Programming Languages and Operating Systems",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/asplos/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "ISCA",
    aliases: [],
    name: "International Symposium on Computer Architecture",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "IEEE/ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/isca/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "ACM SIGOPS ATC",
    aliases: ["USENIX ATC", "ATC"],
    name: "ACM SIGOPS Annual Technical Conference",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/usenix/index.html",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "EuroSys",
    aliases: [],
    name: "European Conference on Computer Systems",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/eurosys/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "HPDC",
    aliases: ["High-Performance Parallel and Distributed Computing"],
    name: "The International ACM Symposium on High-Performance Parallel and Distributed Computing",
    category: "计算机体系结构/并行与分布计算/存储系统",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/hpdc/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 5,
  },
  {
    acronym: "SIGCOMM",
    aliases: [],
    name: "ACM International Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication",
    category: "计算机网络",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/sigcomm/index.html",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 13,
  },
  {
    acronym: "MobiCom",
    aliases: [],
    name: "ACM International Conference on Mobile Computing and Networking",
    category: "计算机网络",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/mobicom/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 13,
  },
  {
    acronym: "INFOCOM",
    aliases: [],
    name: "IEEE International Conference on Computer Communications",
    category: "计算机网络",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/infocom/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 13,
  },
  {
    acronym: "NSDI",
    aliases: [],
    name: "Symposium on Network System Design and Implementation",
    category: "计算机网络",
    publisher: "USENIX",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/nsdi/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 13,
  },
  {
    acronym: "CCS",
    aliases: [],
    name: "ACM Conference on Computer and Communications Security",
    category: "网络与信息安全",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/ccs/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 20,
  },
  {
    acronym: "EUROCRYPT",
    aliases: [],
    name: "International Conference on the Theory and Applications of Cryptographic Techniques",
    category: "网络与信息安全",
    publisher: "Springer",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/eurocrypt/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 20,
  },
  {
    acronym: "S&P",
    aliases: [
      "IEEE S&P",
      "IEEE Symposium on Security and Privacy",
      "Oakland",
      "SP",
    ],
    name: "IEEE Symposium on Security and Privacy",
    category: "网络与信息安全",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/sp/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 20,
  },
  {
    acronym: "CRYPTO",
    aliases: [],
    name: "International Cryptology Conference",
    category: "网络与信息安全",
    publisher: "Springer",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/crypto/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 20,
  },
  {
    acronym: "USENIX Security",
    aliases: ["USENIX Security Symposium", "USS"],
    name: "USENIX Security Symposium",
    category: "网络与信息安全",
    publisher: "USENIX Association",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/uss/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 20,
  },
  {
    acronym: "NDSS",
    aliases: [],
    name: "Network and Distributed System Security Symposium",
    category: "网络与信息安全",
    publisher: "ISOC",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/ndss/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 20,
  },
  {
    acronym: "PLDI",
    aliases: [],
    name: "ACM SIGPLAN Conference on Programming Language Design and Implementation",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/pldi/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "POPL",
    aliases: [],
    name: "ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/popl/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "FSE",
    aliases: ["ESEC/FSE", "SIGSOFT FSE"],
    name: "ACM International Conference on the Foundations of Software Engineering",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/sigsoft/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "SOSP",
    aliases: [],
    name: "ACM Symposium on Operating Systems Principles",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/sosp/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "OOPSLA",
    aliases: ["PACMPL OOPSLA"],
    name: "Conference on Object-Oriented Programming Systems, Languages,and Applications",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/oopsla/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "ASE",
    aliases: [],
    name: "International Conference on Automated Software Engineering",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "IEEE/ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/kbse/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "ICSE",
    aliases: [],
    name: "International Conference on Software Engineering",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "IEEE/ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/icse/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "ISSTA",
    aliases: [],
    name: "International Symposium on Software Testing and Analysis",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/issta/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "OSDI",
    aliases: [],
    name: "USENIX Symposium on Operating Systems Design and Implementations",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "USENIX",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/osdi/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "FM",
    aliases: [],
    name: "International Symposium on Formal Methods",
    category: "软件工程/系统软件/程序设计语言",
    publisher: "FME",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/fm/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 27,
  },
  {
    acronym: "SIGMOD",
    aliases: [],
    name: "ACM SIGMOD Conference",
    category: "数据库/数据挖掘/内容检索",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/sigmod/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 35,
  },
  {
    acronym: "SIGKDD",
    aliases: ["KDD"],
    name: "ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
    category: "数据库/数据挖掘/内容检索",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/kdd/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 35,
  },
  {
    acronym: "ICDE",
    aliases: [],
    name: "IEEE International Conference on Data Engineering",
    category: "数据库/数据挖掘/内容检索",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/icde/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 35,
  },
  {
    acronym: "SIGIR",
    aliases: [],
    name: "International ACM SIGIR Conference on Research and Development in Information Retrieval",
    category: "数据库/数据挖掘/内容检索",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/sigir/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 35,
  },
  {
    acronym: "VLDB",
    aliases: ["PVLDB"],
    name: "International Conference on Very Large Data Bases",
    category: "数据库/数据挖掘/内容检索",
    publisher: "Morgan Kaufmann/ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/vldb/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 35,
  },
  {
    acronym: "STOC",
    aliases: [],
    name: "ACM Symposium on Theory of Computing",
    category: "计算机科学理论",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/stoc/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 41,
  },
  {
    acronym: "SODA",
    aliases: [],
    name: "ACM-SIAM Symposium on Discrete Algorithms",
    category: "计算机科学理论",
    publisher: "SIAM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/soda/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 41,
  },
  {
    acronym: "CAV",
    aliases: [],
    name: "International Conference on Computer Aided Verification",
    category: "计算机科学理论",
    publisher: "Springer",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/cav/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 41,
  },
  {
    acronym: "FOCS",
    aliases: [],
    name: "IEEE Annual Symposium on Foundations of Computer Science",
    category: "计算机科学理论",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/focs/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 41,
  },
  {
    acronym: "LICS",
    aliases: [],
    name: "ACM/IEEE Symposium on Logic in Computer Science",
    category: "计算机科学理论",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/lics/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 41,
  },
  {
    acronym: "ACM MM",
    aliases: ["ACMMM", "MM"],
    name: "ACM International Conference on Multimedia",
    category: "计算机图形学与多媒体",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/mm/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 47,
  },
  {
    acronym: "SIGGRAPH",
    aliases: [],
    name: "ACM Special Interest Group on Computer Graphics",
    category: "计算机图形学与多媒体",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/siggraph/index.html",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 47,
  },
  {
    acronym: "VR",
    aliases: [],
    name: "IEEE Virtual Reality",
    category: "计算机图形学与多媒体",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/vr/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 47,
  },
  {
    acronym: "IEEE VIS",
    aliases: ["VIS", "IEEE Visualization"],
    name: "IEEE Visualization Conference",
    category: "计算机图形学与多媒体",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url:
      "http://dblp.uni-trier.de/db/conf/visualization/index.html",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 47,
  },
  {
    acronym: "AAAI",
    aliases: [],
    name: "AAAI Conference on Artificial Intelligence",
    category: "人工智能",
    publisher: "AAAI",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/aaai/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 57,
  },
  {
    acronym: "NeurIPS",
    aliases: ["NIPS"],
    name: "Conference on Neural Information Processing Systems",
    category: "人工智能",
    publisher: "MIT Press",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/nips/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 57,
  },
  {
    acronym: "ACL",
    aliases: [],
    name: "Annual Meeting of the Association for Computational Linguistics",
    category: "人工智能",
    publisher: "ACL",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/acl/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 57,
  },
  {
    acronym: "CVPR",
    aliases: [],
    name: "IEEE/CVF Computer Vision and Pattern Recognition Conference",
    category: "人工智能",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/cvpr/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 57,
  },
  {
    acronym: "ICCV",
    aliases: [],
    name: "International Conference on Computer Vision",
    category: "人工智能",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/iccv/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 57,
  },
  {
    acronym: "ICML",
    aliases: [],
    name: "International Conference on Machine Learning",
    category: "人工智能",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/icml/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 57,
  },
  {
    acronym: "ICLR",
    aliases: [],
    name: "International Conference on Learning Representations",
    category: "人工智能",
    publisher: "OpenReview",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "https://dblp.uni-trier.de/db/conf/iclr/index.html",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 57,
  },
  {
    acronym: "CSCW",
    aliases: ["PACMHCI CSCW"],
    name: "ACM Conference on Computer Supported Cooperative Work and Social Computing",
    category: "人机交互与普适计算",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/cscw",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 64,
  },
  {
    acronym: "CHI",
    aliases: [],
    name: "ACM Conference on Human Factors in Computing Systems",
    category: "人机交互与普适计算",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/chi",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 64,
  },
  {
    acronym: "UbiComp",
    aliases: ["UbiComp/IMWUT", "IMWUT"],
    name: "ACM International Joint Conference on Pervasive and Ubiquitous Computing",
    category: "人机交互与普适计算",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "https://dblp.uni-trier.de/db/conf/huc/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 64,
  },
  {
    acronym: "UIST",
    aliases: [],
    name: "ACM Symposium on User Interface Software and Technology",
    category: "人机交互与普适计算",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/uist/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 64,
  },
  {
    acronym: "WWW",
    aliases: ["The Web Conference", "WebConf"],
    name: "International World Wide Web Conference",
    category: "交叉/综合/新兴",
    publisher: "ACM",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/www/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 70,
  },
  {
    acronym: "RTSS",
    aliases: [],
    name: "IEEE Real-Time Systems Symposium",
    category: "交叉/综合/新兴",
    publisher: "IEEE",
    rank: "A",
    edition: 7,
    directory_year: 2026,
    updated: "2026-04-09",
    official_venue_url: "http://dblp.uni-trier.de/db/conf/rtss/",
    source_url:
      "https://www.ccf.org.cn/ccf/contentcore/resource/download?ID=112CF3BF7E1140ACEB271ADAED12A67ADFABB8FF099E40C2759502A85C8A281F",
    pdf_page: 70,
  },
] as const;
