/**
 * @owner   src/transport/adapters/desktop-ax-background-dispatch-swift.ts
 * @does    Generate Swift for pid-addressed mouse, text, and key-combo dispatch.
 * @needs   AppKit NSEvent factories, CoreGraphics event APIs, Carbon virtual key constants
 * @feeds   desktop-ax background input Swift generator
 * @breaks  Bad key maps or event ordering can drop input or leave modifier keys pressed.
 */

export function swiftBackgroundDispatcherSupportCode(): string {
  return [
    `struct ScopedWindowInputDispatcher {`,
    `  let targetPID: pid_t`,
    `  let windowNumber: Int`,
    `  let windowFrame: CGRect`,
    `  let keySource = CGEventSource(stateID: .hidSystemState)`,
    `  func click(atScreenPoint point: CGPoint, buttonIndex: Int, clickCount: Int) throws {`,
    `    let button = cgButton(buttonIndex)`,
    `    let types = mouseTypes(buttonIndex)`,
    `    let clampedCount = max(1, min(3, clickCount))`,
    `    for index in 1...clampedCount {`,
    `      let state = index`,
    `      let down = try makeMouse(types.down, point: point, button: button, clickState: state, pressure: 1)`,
    `      let up = try makeMouse(types.up, point: point, button: button, clickState: state, pressure: 0)`,
    `      down.postToPid(targetPID)`,
    `      usleep(30_000)`,
    `      up.postToPid(targetPID)`,
    `      if index < clampedCount { usleep(80_000) }`,
    `    }`,
    `  }`,
    `  func typeText(_ text: String) throws {`,
    `    for character in text {`,
    `      let units = Array(String(character).utf16)`,
    `      try units.withUnsafeBufferPointer { buffer in`,
    `        guard let base = buffer.baseAddress, buffer.count > 0 else { return }`,
    `        let down = try makeKey(keyCode: 0, flags: [], isDown: true)`,
    `        down.keyboardSetUnicodeString(stringLength: buffer.count, unicodeString: base)`,
    `        postKey(down)`,
    `        let up = try makeKey(keyCode: 0, flags: [], isDown: false)`,
    `        up.keyboardSetUnicodeString(stringLength: buffer.count, unicodeString: base)`,
    `        postKey(up)`,
    `      }`,
    `      usleep(1_000)`,
    `    }`,
    `  }`,
    `  func press(_ raw: String) throws {`,
    `    let combo = try KeyCombination.parse(raw)`,
    `    for modifier in combo.modifiers { postKey(try makeKey(keyCode: modifier.virtualKey, flags: modifier.flags, isDown: true)) }`,
    `    let combined = combo.modifiers.reduce(into: CGEventFlags()) { acc, modifier in acc.formUnion(modifier.flags) }`,
    `    postKey(try makeKey(keyCode: combo.keyCode, flags: combined, isDown: true))`,
    `    postKey(try makeKey(keyCode: combo.keyCode, flags: combined, isDown: false))`,
    `    var remaining = combined`,
    `    for modifier in combo.modifiers.reversed() {`,
    `      remaining.subtract(modifier.flags)`,
    `      postKey(try makeKey(keyCode: modifier.virtualKey, flags: remaining, isDown: false))`,
    `    }`,
    `  }`,
    `  private func makeMouse(_ type: CGEventType, point: CGPoint, button: CGMouseButton, clickState: Int, pressure: Double) throws -> CGEvent {`,
    `    let modifierFlags: NSEvent.ModifierFlags = appIsActive(pid: targetPID) ? [] : [.command]`,
    `    guard let nsEvent = NSEvent.mouseEvent(`,
    `      with: nsMouseType(type),`,
    `      location: point,`,
    `      modifierFlags: modifierFlags,`,
    `      timestamp: ProcessInfo.processInfo.systemUptime,`,
    `      windowNumber: windowNumber,`,
    `      context: nil,`,
    `      eventNumber: nextSyntheticMouseEventNumber(),`,
    `      clickCount: clickState,`,
    `      pressure: Float(pressure)`,
    `    ), let event = nsEvent.cgEvent else { throw BackgroundInputError.eventCreate("mouse") }`,
    `    stampWindow(event, targetPID: targetPID, windowNumber: windowNumber, windowFrame: windowFrame, point: point, buttonNumber: Int64(button.rawValue), clickState: Int64(clickState), pressure: pressure)`,
    `    return event`,
    `  }`,
    `  private func nsMouseType(_ type: CGEventType) -> NSEvent.EventType {`,
    `    switch type {`,
    `    case .rightMouseDown: return .rightMouseDown`,
    `    case .rightMouseUp: return .rightMouseUp`,
    `    case .otherMouseDown: return .otherMouseDown`,
    `    case .otherMouseUp: return .otherMouseUp`,
    `    case .leftMouseUp: return .leftMouseUp`,
    `    default: return .leftMouseDown`,
    `    }`,
    `  }`,
    `  private func makeKey(keyCode: CGKeyCode, flags: CGEventFlags, isDown: Bool) throws -> CGEvent {`,
    `    guard let event = CGEvent(keyboardEventSource: keySource, virtualKey: keyCode, keyDown: isDown) else { throw BackgroundInputError.eventCreate("keyboard") }`,
    `    event.flags = flags`,
    `    event.setIntegerValueField(.eventTargetUnixProcessID, value: Int64(targetPID))`,
    `    event.setWindowAddressingFields(windowNumber: windowNumber)`,
    `    return event`,
    `  }`,
    `  private func postKey(_ event: CGEvent) { event.postToPid(targetPID) }`,
    `}`,
    ``,
    `var syntheticMouseEventNumber = 1`,
    `func nextSyntheticMouseEventNumber() -> Int {`,
    `  defer { syntheticMouseEventNumber += 1 }`,
    `  return syntheticMouseEventNumber`,
    `}`,
    ``,
    `func appIsActive(pid: pid_t) -> Bool {`,
    `  NSWorkspace.shared.runningApplications.first { $0.processIdentifier == pid }?.isActive == true`,
    `}`,
    ``,
    `func cgButton(_ index: Int) -> CGMouseButton {`,
    `  if index == 1 { return .right }`,
    `  if index == 2 { return .center }`,
    `  return .left`,
    `}`,
    ``,
    `func mouseTypes(_ index: Int) -> (down: CGEventType, up: CGEventType) {`,
    `  if index == 1 { return (.rightMouseDown, .rightMouseUp) }`,
    `  if index == 2 { return (.otherMouseDown, .otherMouseUp) }`,
    `  return (.leftMouseDown, .leftMouseUp)`,
    `}`,
    ``,
    `struct KeyCombination {`,
    `  let modifiers: [KeyModifier]`,
    `  let keyCode: CGKeyCode`,
    `  static func parse(_ raw: String) throws -> KeyCombination {`,
    `    let segments = raw.split(separator: "+").map { $0.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() }`,
    `    guard let final = segments.last, !final.isEmpty else { throw BackgroundInputError.invalidCombo(raw) }`,
    `    let modifiers = try segments.dropLast().map(KeyModifier.init(token:))`,
    `    return KeyCombination(modifiers: modifiers, keyCode: try keyCode(for: final))`,
    `  }`,
    `  private static func keyCode(for token: String) throws -> CGKeyCode {`,
    `    if token.count == 1, let scalar = token.unicodeScalars.first {`,
    `      switch scalar {`,
    `      case "a"..."z": return alphaKeyCodes[String(scalar)]!`,
    `      case "0"..."9": return digitKeyCodes[String(scalar)]!`,
    `      default: break`,
    `      }`,
    `    }`,
    `    guard let keyCode = namedKeyCodes[token] else { throw BackgroundInputError.unsupportedKey(token) }`,
    `    return keyCode`,
    `  }`,
    `}`,
    ``,
    `struct KeyModifier {`,
    `  let flags: CGEventFlags`,
    `  let virtualKey: CGKeyCode`,
    `  init(token: String) throws {`,
    `    switch token {`,
    `    case "shift": flags = .maskShift; virtualKey = CGKeyCode(kVK_Shift)`,
    `    case "control", "ctrl": flags = .maskControl; virtualKey = CGKeyCode(kVK_Control)`,
    `    case "option", "alt": flags = .maskAlternate; virtualKey = CGKeyCode(kVK_Option)`,
    `    case "command", "cmd", "super", "meta": flags = .maskCommand; virtualKey = CGKeyCode(kVK_Command)`,
    `    default: throw BackgroundInputError.unsupportedKey(token)`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `let alphaKeyCodes: [String: CGKeyCode] = [`,
    `  "a": CGKeyCode(kVK_ANSI_A), "b": CGKeyCode(kVK_ANSI_B), "c": CGKeyCode(kVK_ANSI_C), "d": CGKeyCode(kVK_ANSI_D), "e": CGKeyCode(kVK_ANSI_E), "f": CGKeyCode(kVK_ANSI_F),`,
    `  "g": CGKeyCode(kVK_ANSI_G), "h": CGKeyCode(kVK_ANSI_H), "i": CGKeyCode(kVK_ANSI_I), "j": CGKeyCode(kVK_ANSI_J), "k": CGKeyCode(kVK_ANSI_K), "l": CGKeyCode(kVK_ANSI_L),`,
    `  "m": CGKeyCode(kVK_ANSI_M), "n": CGKeyCode(kVK_ANSI_N), "o": CGKeyCode(kVK_ANSI_O), "p": CGKeyCode(kVK_ANSI_P), "q": CGKeyCode(kVK_ANSI_Q), "r": CGKeyCode(kVK_ANSI_R),`,
    `  "s": CGKeyCode(kVK_ANSI_S), "t": CGKeyCode(kVK_ANSI_T), "u": CGKeyCode(kVK_ANSI_U), "v": CGKeyCode(kVK_ANSI_V), "w": CGKeyCode(kVK_ANSI_W), "x": CGKeyCode(kVK_ANSI_X),`,
    `  "y": CGKeyCode(kVK_ANSI_Y), "z": CGKeyCode(kVK_ANSI_Z),`,
    `]`,
    `let digitKeyCodes: [String: CGKeyCode] = [`,
    `  "0": CGKeyCode(kVK_ANSI_0), "1": CGKeyCode(kVK_ANSI_1), "2": CGKeyCode(kVK_ANSI_2), "3": CGKeyCode(kVK_ANSI_3), "4": CGKeyCode(kVK_ANSI_4),`,
    `  "5": CGKeyCode(kVK_ANSI_5), "6": CGKeyCode(kVK_ANSI_6), "7": CGKeyCode(kVK_ANSI_7), "8": CGKeyCode(kVK_ANSI_8), "9": CGKeyCode(kVK_ANSI_9),`,
    `]`,
    `let namedKeyCodes: [String: CGKeyCode] = [`,
    `  "space": CGKeyCode(kVK_Space), "tab": CGKeyCode(kVK_Tab), "return": CGKeyCode(kVK_Return), "enter": CGKeyCode(kVK_Return),`,
    `  "escape": CGKeyCode(kVK_Escape), "esc": CGKeyCode(kVK_Escape), "delete": CGKeyCode(kVK_Delete), "backspace": CGKeyCode(kVK_Delete),`,
    `  "forward-delete": CGKeyCode(kVK_ForwardDelete), "left": CGKeyCode(kVK_LeftArrow), "right": CGKeyCode(kVK_RightArrow), "up": CGKeyCode(kVK_UpArrow),`,
    `  "down": CGKeyCode(kVK_DownArrow), "home": CGKeyCode(kVK_Home), "end": CGKeyCode(kVK_End), "pageup": CGKeyCode(kVK_PageUp), "pagedown": CGKeyCode(kVK_PageDown),`,
    `]`,
  ].join("\n");
}
