/**
 * @owner   src/transport/adapters/desktop-ax-background-window-swift.ts
 * @does    Generate Swift helpers for target window lookup and CGEvent window addressing.
 * @needs   AppKit/CoreGraphics runtime APIs
 * @feeds   desktop-ax background input Swift generator
 * @breaks  Incorrect window fields can send background input to the wrong macOS window.
 */

export function swiftBackgroundWindowSupportCode(): string {
  return [
    `enum BackgroundInputError: Error, CustomStringConvertible {`,
    `  case eventCreate(String)`,
    `  case unsupportedKey(String)`,
    `  case invalidCombo(String)`,
    `  var description: String {`,
    `    switch self {`,
    `    case .eventCreate(let label): return "event_create_failed:" + label`,
    `    case .unsupportedKey(let key): return "unsupported_key:" + key`,
    `    case .invalidCombo(let combo): return "invalid_key_combo:" + combo`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `func number(_ dict: NSDictionary, _ key: CFString) -> NSNumber? { dict[key as String] as? NSNumber }`,
    ``,
    `func rect(_ dict: NSDictionary) -> CGRect? {`,
    `  guard let raw = dict[kCGWindowBounds as String] as? NSDictionary else { return nil }`,
    `  var rect = CGRect.zero`,
    `  return CGRectMakeWithDictionaryRepresentation(raw, &rect) ? rect : nil`,
    `}`,
    ``,
    `func targetWindow(pid: pid_t) -> (id: CGWindowID, frame: CGRect)? {`,
    `  guard let list = CGWindowListCopyWindowInfo([.optionOnScreenOnly, .excludeDesktopElements], kCGNullWindowID) as? [NSDictionary] else { return nil }`,
    `  for item in list {`,
    `    guard number(item, kCGWindowOwnerPID)?.int32Value == pid else { continue }`,
    `    guard let idNumber = number(item, kCGWindowNumber), let frame = rect(item), !frame.isEmpty else { continue }`,
    `    let windowId = CGWindowID(idNumber.uint32Value)`,
    `    if requestedWindowNumber == 0 || requestedWindowNumber == Int(windowId) { return (windowId, frame) }`,
    `  }`,
    `  return nil`,
    `}`,
    ``,
    `func requestedScreenPoint(windowFrame: CGRect) -> CGPoint {`,
    `  if coordinateSpace == "screen" { return CGPoint(x: inputX, y: inputY) }`,
    `  return CGPoint(x: windowFrame.origin.x + inputX, y: windowFrame.origin.y + inputY)`,
    `}`,
    ``,
    `func windowLocalPoint(fromScreen point: CGPoint, windowFrame: CGRect) -> CGPoint {`,
    `  CGPoint(x: point.x - windowFrame.minX, y: point.y - windowFrame.minY)`,
    `}`,
    ``,
    `func quartzWindowPoint(fromTopLeftLocal point: CGPoint, windowHeight: CGFloat) -> CGPoint {`,
    `  CGPoint(x: point.x, y: windowHeight - point.y)`,
    `}`,
    ``,
    `func emitSuccess(window: (id: CGWindowID, frame: CGRect), running: NSRunningApplication, wasFrontmost: Bool, extra: [String: Any]) {`,
    `  var payload: [String: Any?] = [`,
    `    "found": true,`,
    `    "posted": true,`,
    `    "mode": commandMode,`,
    `    "action": requestedAction,`,
    `    "pid": Int(running.processIdentifier),`,
    `    "windowNumber": Int(window.id),`,
    `    "wasFrontmost": wasFrontmost,`,
    `    "backgroundActivated": !wasFrontmost,`,
    `    "setWindowLocationAvailable": ScopedWindowLocalPointWriter.isAvailable`,
    `  ]`,
    `  for (key, value) in extra { payload[key] = value }`,
    `  emit(payload)`,
    `}`,
    ``,
    `enum ScopedWindowLocalPointWriter {`,
    `  private typealias SetWindowLocationFn = @convention(c) (CGEvent, CGPoint) -> Void`,
    `  private static let setWindowLocation: SetWindowLocationFn? = {`,
    `    _ = dlopen("/System/Library/PrivateFrameworks/SkyLight.framework/SkyLight", RTLD_LAZY)`,
    `    guard let symbol = dlsym(UnsafeMutableRawPointer(bitPattern: -2), "CGEventSetWindowLocation") else { return nil }`,
    `    return unsafeBitCast(symbol, to: SetWindowLocationFn.self)`,
    `  }()`,
    `  static var isAvailable: Bool { setWindowLocation != nil }`,
    `  @discardableResult static func setPoint(_ point: CGPoint, on event: CGEvent) -> Bool {`,
    `    guard let setWindowLocation else { return false }`,
    `    setWindowLocation(event, point)`,
    `    return true`,
    `  }`,
    `}`,
    ``,
    `extension CGEvent {`,
    `  private static let targetWindowNumberField = CGEventField(rawValue: 51)`,
    `  private static let privateWindowRoutingField = CGEventField(rawValue: 58)`,
    `  func setWindowAddressingFields(windowNumber: Int) {`,
    `    if let field = Self.targetWindowNumberField { setIntegerValueField(field, value: Int64(windowNumber)) }`,
    `    if let field = Self.privateWindowRoutingField { setIntegerValueField(field, value: 1) }`,
    `  }`,
    `}`,
    ``,
    `func stampWindow(_ event: CGEvent, targetPID: pid_t, windowNumber: Int, windowFrame: CGRect, point: CGPoint, buttonNumber: Int64, clickState: Int64, pressure: Double) {`,
    `  event.location = point`,
    `  event.setIntegerValueField(.eventTargetUnixProcessID, value: Int64(targetPID))`,
    `  event.setIntegerValueField(.mouseEventButtonNumber, value: buttonNumber)`,
    `  event.setIntegerValueField(.mouseEventClickState, value: clickState)`,
    `  event.setIntegerValueField(CGEventField(rawValue: 7)!, value: 3)`,
    `  event.setDoubleValueField(.mouseEventPressure, value: pressure)`,
    `  event.setIntegerValueField(.mouseEventWindowUnderMousePointer, value: Int64(windowNumber))`,
    `  event.setIntegerValueField(.mouseEventWindowUnderMousePointerThatCanHandleThisEvent, value: Int64(windowNumber))`,
    `  event.setWindowAddressingFields(windowNumber: windowNumber)`,
    `  let local = windowLocalPoint(fromScreen: point, windowFrame: windowFrame)`,
    `  _ = ScopedWindowLocalPointWriter.setPoint(quartzWindowPoint(fromTopLeftLocal: local, windowHeight: windowFrame.height), on: event)`,
    `}`,
  ].join("\n");
}
