/**
 * @owner   src/transport/adapters/desktop-ax-background-activation-swift.ts
 * @does    Generate Swift for per-process focus suppression and background window priming.
 * @needs   AppKit/CoreGraphics event tap APIs, window event stamping helpers
 * @feeds   desktop-ax background input Swift generator
 * @breaks  Failed tap installation can steal user focus or prevent background activation.
 */

export function swiftBackgroundActivationSupportCode(): string {
  return [
    `final class ScopedWindowActivationSession {`,
    `  enum TapKind { case previous, target }`,
    `  private enum Phase { case deliveringToTarget, holding, finished }`,
    `  final class TapContext { let session: ScopedWindowActivationSession; let kind: TapKind; init(session: ScopedWindowActivationSession, kind: TapKind) { self.session = session; self.kind = kind } }`,
    `  private let targetPID: pid_t`,
    `  private let lock = NSLock()`,
    `  private var phase: Phase = .deliveringToTarget`,
    `  private var taps: [CFMachPort] = []`,
    `  private var contexts: [TapContext] = []`,
    `  private var finished = false`,
    `  private init(targetPID: pid_t) { self.targetPID = targetPID }`,
    `  static func start(targetPID: pid_t) -> ScopedWindowActivationSession? {`,
    `    guard let previous = NSWorkspace.shared.frontmostApplication, previous.processIdentifier != targetPID else { return ScopedWindowActivationSession(targetPID: targetPID) }`,
    `    let session = ScopedWindowActivationSession(targetPID: targetPID)`,
    `    guard session.installTap(kind: .previous, pid: previous.processIdentifier), session.installTap(kind: .target, pid: targetPID) else { session.finish(); return nil }`,
    `    return session`,
    `  }`,
    `  func beginTargetDelivery() { setPhase(.deliveringToTarget) }`,
    `  func holdFocusSuppressionUntilFinish() { setPhase(.holding) }`,
    `  static func activateWindow(targetPID: pid_t, windowNumber: Int, windowFrame: CGRect) {`,
    `    postWindowActivationEvent(targetPID: targetPID, windowNumber: windowNumber)`,
    `    postWindowCenterPrimer(targetPID: targetPID, windowNumber: windowNumber, windowFrame: windowFrame)`,
    `  }`,
    `  private static func postWindowActivationEvent(targetPID: pid_t, windowNumber: Int) {`,
    `    guard windowNumber != 0 else { return }`,
    `    let event = NSEvent.otherEvent(with: .appKitDefined, location: .zero, modifierFlags: [], timestamp: 0, windowNumber: windowNumber, context: nil, subtype: Int16(1), data1: 0, data2: 0)?.cgEvent`,
    `    guard let event else { return }`,
    `    event.setWindowAddressingFields(windowNumber: windowNumber)`,
    `    event.postToPid(targetPID)`,
    `    usleep(20_000)`,
    `  }`,
    `  private static func postWindowCenterPrimer(targetPID: pid_t, windowNumber: Int, windowFrame: CGRect) {`,
    `    guard windowNumber != 0, windowFrame.width > 0, windowFrame.height > 0 else { return }`,
    `    let point = CGPoint(x: windowFrame.midX, y: windowFrame.midY)`,
    `    postMouse(.leftMouseDown, targetPID: targetPID, windowNumber: windowNumber, windowFrame: windowFrame, point: point, clickState: 1, pressure: 1)`,
    `    usleep(30_000)`,
    `    postMouse(.leftMouseUp, targetPID: targetPID, windowNumber: windowNumber, windowFrame: windowFrame, point: point, clickState: 1, pressure: 0)`,
    `    usleep(20_000)`,
    `  }`,
    `  private static func postMouse(_ type: CGEventType, targetPID: pid_t, windowNumber: Int, windowFrame: CGRect, point: CGPoint, clickState: Int64, pressure: Double) {`,
    `    guard let event = CGEvent(mouseEventSource: nil, mouseType: type, mouseCursorPosition: point, mouseButton: .left) else { return }`,
    `    stampWindow(event, targetPID: targetPID, windowNumber: windowNumber, windowFrame: windowFrame, point: point, buttonNumber: 0, clickState: clickState, pressure: pressure)`,
    `    event.postToPid(targetPID)`,
    `  }`,
    `  func restoreBackgroundActivationIfNeeded(windowNumber: Int) {`,
    `    guard windowNumber != 0 else { return }`,
    `    guard NSWorkspace.shared.frontmostApplication?.processIdentifier != targetPID else { return }`,
    `    beginTargetDelivery()`,
    `    let event = NSEvent.otherEvent(with: .appKitDefined, location: .zero, modifierFlags: [], timestamp: 0, windowNumber: windowNumber, context: nil, subtype: NSEvent.EventSubtype.applicationDeactivated.rawValue, data1: 0, data2: 0)?.cgEvent`,
    `    guard let event else { return }`,
    `    event.setWindowAddressingFields(windowNumber: windowNumber)`,
    `    event.postToPid(targetPID)`,
    `    usleep(20_000)`,
    `  }`,
    `  func finish() {`,
    `    let shouldFinish: Bool = lock.withLock { if finished { return false }; finished = true; phase = .finished; return true }`,
    `    guard shouldFinish else { return }`,
    `    for tap in taps { CFMachPortInvalidate(tap) }`,
    `    taps.removeAll(); contexts.removeAll()`,
    `  }`,
    `  private func installTap(kind: TapKind, pid: pid_t) -> Bool {`,
    `    let context = TapContext(session: self, kind: kind)`,
    `    let pointer = Unmanaged.passUnretained(context).toOpaque()`,
    `    guard let tap = CGEvent.tapCreateForPid(pid: pid, place: .headInsertEventTap, options: .defaultTap, eventsOfInterest: CGEventMask.max, callback: scopedWindowActivationEventTapCallback, userInfo: pointer) else { return false }`,
    `    guard let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0) else { CFMachPortInvalidate(tap); return false }`,
    `    CFRunLoopAddSource(CFRunLoopGetCurrent(), source, CFRunLoopMode.commonModes)`,
    `    CGEvent.tapEnable(tap: tap, enable: true)`,
    `    contexts.append(context); taps.append(tap)`,
    `    return true`,
    `  }`,
    `  func shouldDrop(kind: TapKind, type: CGEventType) -> Bool {`,
    `    guard type.rawValue == 13 || type.rawValue == 19 || type.rawValue == 20 else { return false }`,
    `    let current = lock.withLock { phase }`,
    `    switch current {`,
    `    case .deliveringToTarget, .holding: return kind == .previous`,
    `    case .finished: return false`,
    `    }`,
    `  }`,
    `  private func setPhase(_ next: Phase) { lock.withLock { phase = next } }`,
    `}`,
    ``,
    `let scopedWindowActivationEventTapCallback: CGEventTapCallBack = { _, type, event, rawContext in`,
    `  guard let rawContext else { return Unmanaged.passUnretained(event) }`,
    `  let context = Unmanaged<ScopedWindowActivationSession.TapContext>.fromOpaque(rawContext).takeUnretainedValue()`,
    `  if context.session.shouldDrop(kind: context.kind, type: type) { return nil }`,
    `  return Unmanaged.passUnretained(event)`,
    `}`,
  ].join("\n");
}
