/**
 * Agents CLI command — auto-generate AGENTS.md for capability discovery.
 *
 * Command:
 *   unicli agents generate  — Generate AGENTS.md from adapter registry
 *
 * Options:
 *   --output <path>  — Output file path (default: AGENTS.md in project root)
 */

import { Command } from "commander";
import chalk from "chalk";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getAllAdapters, listCommands } from "../registry.js";
import { VERSION } from "../constants.js";

export function registerAgentsCommand(program: Command): void {
  const agents = program
    .command("agents")
    .description("AGENTS.md generation and management");

  agents
    .command("generate")
    .description("Auto-generate AGENTS.md from loaded adapters")
    .option("--output <path>", "output file path", "AGENTS.md")
    .option(
      "--for <harness>",
      "target harness format (claude|cursor|codex|goose|generic)",
    )
    .action((opts: { output: string; for?: string }) => {
      const harness = opts.for ?? "claude";
      if (
        !["claude", "cursor", "codex", "goose", "generic"].includes(harness)
      ) {
        console.error(
          chalk.red(
            `Unknown harness: ${harness}. Available: claude, cursor, codex, goose, generic`,
          ),
        );
        process.exitCode = 1;
        return;
      }
      const adapters = getAllAdapters();
      const commands = listCommands();

      if (adapters.length === 0) {
        console.error(chalk.red("No adapters loaded"));
        process.exit(1);
      }

      const siteCount = adapters.length;
      const cmdCount = commands.length;
      const date = new Date().toISOString().split("T")[0];

      // Group adapters by category
      const categories = new Map<string, typeof adapters>();
      for (const adapter of adapters) {
        const cat = adapter.category ?? "Uncategorized";
        const group = categories.get(cat);
        if (group) {
          group.push(adapter);
        } else {
          categories.set(cat, [adapter]);
        }
      }

      // Build AGENTS.md content
      const lines: string[] = [];

      lines.push(
        `<!-- unicli v${VERSION} | ${siteCount} sites | ${cmdCount} commands -->`,
      );
      lines.push("# AGENTS.md — Uni-CLI Capability Discovery");
      lines.push("");
      lines.push("> Auto-generated. Do not edit manually.");
      lines.push("> Regenerate with: `unicli agents generate`");
      lines.push("");

      // Sites by Category
      lines.push("## Sites by Category");
      lines.push("");

      const sortedCategories = Array.from(categories.entries()).sort(
        ([a], [b]) => a.localeCompare(b),
      );

      for (const [category, adaptersInCat] of sortedCategories) {
        lines.push(`### ${category}`);
        lines.push("");
        lines.push("| Site | Commands | Auth | Description |");
        lines.push("|------|----------|------|-------------|");

        const sorted = adaptersInCat.sort((a, b) =>
          a.name.localeCompare(b.name),
        );

        for (const adapter of sorted) {
          const cmdNames = Object.keys(adapter.commands).sort().join(", ");
          const auth = adapter.strategy ?? "public";
          const desc = adapter.description ?? "";
          lines.push(`| ${adapter.name} | ${cmdNames} | ${auth} | ${desc} |`);
        }

        lines.push("");
      }

      // All Commands
      lines.push("## All Commands");
      lines.push("");
      lines.push("| Site | Command | Description | Auth |");
      lines.push("|------|---------|-------------|------|");

      for (const cmd of commands) {
        const auth = cmd.auth ? "yes" : "no";
        lines.push(
          `| ${cmd.site} | ${cmd.command} | ${cmd.description} | ${auth} |`,
        );
      }

      lines.push("");
      lines.push("---");
      lines.push(`<!-- Generated by Uni-CLI v${VERSION} on ${date} -->`);
      lines.push("");

      // Transform content based on target harness
      let content: string;
      const baseContent = lines.join("\n");

      switch (harness) {
        case "cursor": {
          // Cursor Rules format — .cursorrules file
          const cursorLines = [
            "# Uni-CLI Integration Rules",
            "",
            `Uni-CLI provides ${cmdCount} commands across ${siteCount} sites.`,
            "Use `unicli <site> <command>` to interact with websites and services.",
            "Pipe output is always JSON — no flags needed.",
            "",
            "## Available Sites",
            "",
          ];
          for (const adapter of adapters) {
            const cmds = Object.keys(adapter.commands).sort().join(", ");
            cursorLines.push(`- **${adapter.name}**: ${cmds}`);
          }
          cursorLines.push("");
          cursorLines.push("## Error Handling");
          cursorLines.push(
            "On failure, unicli outputs structured JSON to stderr with `adapter_path` and `suggestion` fields.",
          );
          cursorLines.push(
            "Read the YAML adapter at that path to understand and fix the issue.",
          );
          content = cursorLines.join("\n");
          break;
        }
        case "codex": {
          // Codex-optimized format — concise, tool-use oriented
          const codexLines = [
            `# unicli — ${siteCount} sites, ${cmdCount} commands`,
            "",
            "## Usage",
            "```",
            "unicli <site> <command> [args] [--json]",
            "```",
            "",
            "Piped output auto-switches to JSON. Exit codes follow sysexits.h.",
            "",
            "## Sites",
            "",
          ];
          for (const adapter of adapters) {
            codexLines.push(`### ${adapter.name}`);
            for (const [cmd, info] of Object.entries(adapter.commands)) {
              const desc = (info as { description?: string }).description ?? "";
              codexLines.push(`- \`unicli ${adapter.name} ${cmd}\` — ${desc}`);
            }
          }
          content = codexLines.join("\n");
          break;
        }
        case "goose": {
          // Goose recipe format
          const gooseLines = [
            "name: unicli",
            `description: CLI interface to ${siteCount} websites and services`,
            "version: " + VERSION,
            "tools:",
          ];
          for (const cmd of commands) {
            gooseLines.push(`  - name: unicli_${cmd.site}_${cmd.command}`);
            gooseLines.push(`    command: unicli ${cmd.site} ${cmd.command}`);
            gooseLines.push(`    description: ${cmd.description}`);
          }
          content = gooseLines.join("\n");
          break;
        }
        case "generic":
          content = baseContent;
          break;
        default:
          content = baseContent;
      }

      const outPath = resolve(opts.output);
      writeFileSync(outPath, content, "utf-8");

      // Summary to stderr so it doesn't pollute piped output
      console.error(
        chalk.green(
          `Generated ${outPath} (${siteCount} sites, ${cmdCount} commands, format: ${harness})`,
        ),
      );
    });
}
