/**
 * Agents CLI command — auto-generate platform-specific discovery files.
 *
 * Command:
 *   unicli agents generate  — Generate discovery files from adapter registry
 *
 * Options:
 *   --output <path>  — Output file path (default: stdout)
 *   --for <platform> — Target platform format
 *
 * Supported platforms:
 *   generic    — Standard AGENTS.md (default)
 *   claude     — CLAUDE.md snippet with MCP config JSON
 *   codex      — AGENTS.md + .codex/config.toml snippet
 *   openclaw   — ClawHub-compatible JSON metadata
 *   hermes     — Context file + config.yaml snippet
 *   opencode   — opencode.jsonc snippet
 *   cursor     — .cursorrules format
 *   goose      — Goose recipe YAML
 */

import { Command } from "commander";
import chalk from "chalk";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getAllAdapters, listCommands } from "../registry.js";
import { VERSION } from "../constants.js";
import type { AdapterManifest } from "../types.js";

// ── Template context shared by all formatters ─────────────────────────────

interface TemplateContext {
  sites: number;
  commands: number;
  version: string;
  date: string;
  adapters: AdapterManifest[];
  commandList: ReturnType<typeof listCommands>;
}

// ── MCP config snippet (reused by multiple platforms) ─────────────────────

function mcpConfigObject(): Record<string, unknown> {
  return {
    command: "npx",
    args: ["-y", "@zenalexa/unicli", "mcp", "serve"],
    env: {},
  };
}

// ── Platform format generators ────────────────────────────────────────────

function formatGeneric(ctx: TemplateContext): string {
  const lines: string[] = [];

  lines.push(
    `<!-- unicli v${ctx.version} | ${ctx.sites} sites | ${ctx.commands} commands -->`,
  );
  lines.push("# AGENTS.md — Uni-CLI Capability Discovery");
  lines.push("");
  lines.push("> Auto-generated. Do not edit manually.");
  lines.push("> Regenerate with: `unicli agents generate`");
  lines.push("");

  // Installation
  lines.push("## Installation");
  lines.push("");
  lines.push("```bash");
  lines.push("npm i -g @zenalexa/unicli");
  lines.push("```");
  lines.push("");

  // Sites by Category
  lines.push("## Sites by Category");
  lines.push("");

  const categories = new Map<string, AdapterManifest[]>();
  for (const adapter of ctx.adapters) {
    const cat = adapter.category ?? "Uncategorized";
    const group = categories.get(cat);
    if (group) {
      group.push(adapter);
    } else {
      categories.set(cat, [adapter]);
    }
  }

  const sortedCategories = Array.from(categories.entries()).sort(([a], [b]) =>
    a.localeCompare(b),
  );

  for (const [category, adaptersInCat] of sortedCategories) {
    lines.push(`### ${category}`);
    lines.push("");
    lines.push("| Site | Commands | Auth | Description |");
    lines.push("|------|----------|------|-------------|");

    const sorted = adaptersInCat.sort((a, b) => a.name.localeCompare(b.name));

    for (const adapter of sorted) {
      const cmdNames = Object.keys(adapter.commands).sort().join(", ");
      const auth = adapter.strategy ?? "public";
      const desc = adapter.description ?? "";
      lines.push(`| ${adapter.name} | ${cmdNames} | ${auth} | ${desc} |`);
    }

    lines.push("");
  }

  // All Commands
  lines.push("## All Commands");
  lines.push("");
  lines.push("| Site | Command | Description | Auth |");
  lines.push("|------|---------|-------------|------|");

  for (const cmd of ctx.commandList) {
    const auth = cmd.auth ? "yes" : "no";
    lines.push(
      `| ${cmd.site} | ${cmd.command} | ${cmd.description} | ${auth} |`,
    );
  }

  lines.push("");

  // Self-repair
  lines.push("## Self-Repair");
  lines.push("");
  lines.push(
    "When a command fails, unicli outputs structured JSON to stderr with `adapter_path` and `suggestion` fields.",
  );
  lines.push(
    "Read the YAML adapter at that path to understand and fix the issue.",
  );
  lines.push("Run `unicli repair <site> <command>` for automated repair.");
  lines.push("");

  lines.push("---");
  lines.push(`<!-- Generated by Uni-CLI v${ctx.version} on ${ctx.date} -->`);
  lines.push("");

  return lines.join("\n");
}

function formatClaude(ctx: TemplateContext): string {
  const lines: string[] = [];

  lines.push("# Uni-CLI Integration");
  lines.push("");
  lines.push(
    `Uni-CLI provides ${ctx.commands} commands across ${ctx.sites} sites via CLI.`,
  );
  lines.push("Piped output is always JSON — no flags needed.");
  lines.push("");

  lines.push("## Installation");
  lines.push("");
  lines.push("```bash");
  lines.push("npm i -g @zenalexa/unicli");
  lines.push("```");
  lines.push("");

  lines.push("## MCP Server Configuration");
  lines.push("");
  lines.push(
    "Add to your `claude_desktop_config.json` or project `.mcp.json`:",
  );
  lines.push("");
  lines.push("```json");
  lines.push(
    JSON.stringify({ mcpServers: { unicli: mcpConfigObject() } }, null, 2),
  );
  lines.push("```");
  lines.push("");

  lines.push("## Usage");
  lines.push("");
  lines.push("```bash");
  lines.push("unicli <site> <command> [args]");
  lines.push("```");
  lines.push("");

  // Compact site list
  lines.push("## Available Sites");
  lines.push("");
  for (const adapter of ctx.adapters) {
    const cmds = Object.keys(adapter.commands).sort().join(", ");
    lines.push(`- **${adapter.name}**: ${cmds}`);
  }
  lines.push("");

  // Self-repair
  lines.push("## Self-Repair");
  lines.push("");
  lines.push(
    "On failure, unicli outputs structured JSON to stderr with `adapter_path` and `suggestion`.",
  );
  lines.push(
    "Read the YAML adapter at that path, fix the issue, and retry. Or run `unicli repair <site> <command>`.",
  );
  lines.push("");

  lines.push(
    `<!-- Generated by Uni-CLI v${ctx.version} on ${ctx.date} -->`,
  );
  lines.push("");

  return lines.join("\n");
}

function formatCodex(ctx: TemplateContext): string {
  const lines: string[] = [];

  // TOML MCP config snippet
  lines.push("# .codex/config.toml — MCP server configuration");
  lines.push("");
  lines.push("[mcp_servers.unicli]");
  lines.push('command = "npx"');
  lines.push('args = ["-y", "@zenalexa/unicli", "mcp", "serve"]');
  lines.push("");
  lines.push("# ---");
  lines.push("");

  // AGENTS.md portion
  lines.push(`# unicli — ${ctx.sites} sites, ${ctx.commands} commands`);
  lines.push("");
  lines.push("## Installation");
  lines.push("");
  lines.push("```bash");
  lines.push("npm i -g @zenalexa/unicli");
  lines.push("```");
  lines.push("");
  lines.push("## Usage");
  lines.push("");
  lines.push("```");
  lines.push("unicli <site> <command> [args] [--json]");
  lines.push("```");
  lines.push("");
  lines.push("Piped output auto-switches to JSON. Exit codes follow sysexits.h.");
  lines.push("");

  lines.push("## Sites");
  lines.push("");
  for (const adapter of ctx.adapters) {
    lines.push(`### ${adapter.name}`);
    for (const [cmd, info] of Object.entries(adapter.commands)) {
      const desc = info.description ?? "";
      lines.push(`- \`unicli ${adapter.name} ${cmd}\` — ${desc}`);
    }
  }
  lines.push("");

  lines.push("## Self-Repair");
  lines.push("");
  lines.push(
    "On failure, structured JSON errors include `adapter_path` and `suggestion`.",
  );
  lines.push(
    "Read the adapter file, fix, and retry. Automated: `unicli repair <site> <command>`.",
  );
  lines.push("");

  return lines.join("\n");
}

function formatOpenclaw(ctx: TemplateContext): string {
  const skills = ctx.commandList.map((cmd) => ({
    name: `unicli_${cmd.site}_${cmd.command}`,
    display_name: `${cmd.site} ${cmd.command}`,
    description: cmd.description,
    command: `unicli ${cmd.site} ${cmd.command}`,
    auth_required: cmd.auth,
    tags: [cmd.site, cmd.type],
  }));

  const metadata = {
    name: "unicli",
    version: ctx.version,
    description: `CLI interface to ${ctx.sites} websites and services`,
    install: "npm i -g @zenalexa/unicli",
    mcp: mcpConfigObject(),
    self_repair: {
      description:
        "On failure, read the YAML adapter at the error's adapter_path and fix the selector or URL",
      command: "unicli repair <site> <command>",
    },
    site_count: ctx.sites,
    command_count: ctx.commands,
    skills,
    generated: ctx.date,
  };

  return JSON.stringify(metadata, null, 2) + "\n";
}

function formatHermes(ctx: TemplateContext): string {
  const lines: string[] = [];

  // YAML config snippet
  lines.push("# config.yaml — MCP server configuration for Hermes");
  lines.push("mcp_servers:");
  lines.push("  unicli:");
  lines.push('    command: "npx"');
  lines.push("    args:");
  lines.push('      - "-y"');
  lines.push('      - "@zenalexa/unicli"');
  lines.push('      - "mcp"');
  lines.push('      - "serve"');
  lines.push("");
  lines.push("# ---");
  lines.push("");

  // Context file
  lines.push("# Uni-CLI Context");
  lines.push("");
  lines.push(
    `Uni-CLI provides ${ctx.commands} commands across ${ctx.sites} sites.`,
  );
  lines.push("");
  lines.push("## Installation");
  lines.push("");
  lines.push("```bash");
  lines.push("npm i -g @zenalexa/unicli");
  lines.push("```");
  lines.push("");
  lines.push("## Usage");
  lines.push("");
  lines.push("```bash");
  lines.push("unicli <site> <command> [args]");
  lines.push("```");
  lines.push("");

  lines.push("## Available Sites");
  lines.push("");
  for (const adapter of ctx.adapters) {
    const cmds = Object.keys(adapter.commands).sort().join(", ");
    lines.push(`- ${adapter.name}: ${cmds}`);
  }
  lines.push("");

  lines.push("## Self-Repair");
  lines.push("");
  lines.push(
    "On failure, read the YAML adapter at the error's `adapter_path` field and fix the issue.",
  );
  lines.push("Automated repair: `unicli repair <site> <command>`.");
  lines.push("");

  return lines.join("\n");
}

function formatOpencode(ctx: TemplateContext): string {
  const config = {
    $schema: "https://opencode.ai/config.schema.json",
    mcpServers: {
      unicli: {
        command: "npx",
        args: ["-y", "@zenalexa/unicli", "mcp", "serve"],
      },
    },
    // Context comments embedded as description fields
    _unicli: {
      version: ctx.version,
      sites: ctx.sites,
      commands: ctx.commands,
      install: "npm i -g @zenalexa/unicli",
      usage: "unicli <site> <command> [args]",
      self_repair:
        "On failure, read YAML adapter at error's adapter_path and fix. Or: unicli repair <site> <command>",
    },
  };

  // JSONC format — with comments
  const lines: string[] = [];
  lines.push("// opencode.jsonc — Uni-CLI MCP server configuration");
  lines.push(`// ${ctx.sites} sites, ${ctx.commands} commands available`);
  lines.push(`// Install: npm i -g @zenalexa/unicli`);
  lines.push(JSON.stringify(config, null, 2));
  lines.push("");

  return lines.join("\n");
}

function formatCursor(ctx: TemplateContext): string {
  const lines = [
    "# Uni-CLI Integration Rules",
    "",
    `Uni-CLI provides ${ctx.commands} commands across ${ctx.sites} sites.`,
    "Use `unicli <site> <command>` to interact with websites and services.",
    "Piped output is always JSON — no flags needed.",
    "",
    "## Installation",
    "",
    "```bash",
    "npm i -g @zenalexa/unicli",
    "```",
    "",
    "## Available Sites",
    "",
  ];
  for (const adapter of ctx.adapters) {
    const cmds = Object.keys(adapter.commands).sort().join(", ");
    lines.push(`- **${adapter.name}**: ${cmds}`);
  }
  lines.push("");
  lines.push("## Self-Repair");
  lines.push(
    "On failure, unicli outputs structured JSON to stderr with `adapter_path` and `suggestion` fields.",
  );
  lines.push(
    "Read the YAML adapter at that path to understand and fix the issue.",
  );
  lines.push("Automated: `unicli repair <site> <command>`.");
  lines.push("");

  return lines.join("\n");
}

function formatGoose(ctx: TemplateContext): string {
  const lines = [
    "name: unicli",
    `description: ${JSON.stringify(`CLI interface to ${ctx.sites} websites and services`)}`,
    `version: ${JSON.stringify(ctx.version)}`,
    `install: ${JSON.stringify("npm i -g @zenalexa/unicli")}`,
    `self_repair: ${JSON.stringify("unicli repair <site> <command>")}`,
    "tools:",
  ];
  for (const cmd of ctx.commandList) {
    lines.push(`  - name: unicli_${cmd.site}_${cmd.command}`);
    lines.push(`    command: ${JSON.stringify(`unicli ${cmd.site} ${cmd.command}`)}`);
    lines.push(`    description: ${JSON.stringify(cmd.description)}`);
  }
  return lines.join("\n") + "\n";
}

// ── Platform registry ─────────────────────────────────────────────────────

const PLATFORMS = [
  "generic",
  "claude",
  "codex",
  "openclaw",
  "hermes",
  "opencode",
  "cursor",
  "goose",
] as const;

type Platform = (typeof PLATFORMS)[number];

const formatters: Record<Platform, (ctx: TemplateContext) => string> = {
  generic: formatGeneric,
  claude: formatClaude,
  codex: formatCodex,
  openclaw: formatOpenclaw,
  hermes: formatHermes,
  opencode: formatOpencode,
  cursor: formatCursor,
  goose: formatGoose,
};

// ── Command registration ──────────────────────────────────────────────────

export function registerAgentsCommand(program: Command): void {
  const agents = program
    .command("agents")
    .description("AGENTS.md generation and management");

  agents
    .command("generate")
    .description("Auto-generate discovery files from loaded adapters")
    .option("--output <path>", "write to file instead of stdout")
    .option(
      "--for <platform>",
      `target platform (${PLATFORMS.join("|")})`,
      "generic",
    )
    .action((opts: { output?: string; for: string }) => {
      const platform = opts.for as Platform;
      if (!PLATFORMS.includes(platform)) {
        console.error(
          chalk.red(
            `Unknown platform: ${platform}. Available: ${PLATFORMS.join(", ")}`,
          ),
        );
        process.exitCode = 1;
        return;
      }

      const adapters = getAllAdapters();
      const commandList = listCommands();

      if (adapters.length === 0) {
        console.error(chalk.red("No adapters loaded"));
        process.exit(1);
      }

      const ctx: TemplateContext = {
        sites: adapters.length,
        commands: commandList.length,
        version: VERSION,
        date: new Date().toISOString().split("T")[0],
        adapters,
        commandList,
      };

      const content = formatters[platform](ctx);

      if (opts.output) {
        const outPath = resolve(opts.output);
        writeFileSync(outPath, content, "utf-8");
        console.error(
          chalk.green(
            `Generated ${outPath} (${ctx.sites} sites, ${ctx.commands} commands, format: ${platform})`,
          ),
        );
      } else {
        // Print to stdout so agents can redirect
        process.stdout.write(content);
      }
    });
}
