/**
 * Agents CLI command — auto-generate AGENTS.md for capability discovery.
 *
 * Command:
 *   unicli agents generate  — Generate AGENTS.md from adapter registry
 *
 * Options:
 *   --output <path>  — Output file path (default: AGENTS.md in project root)
 */

import { Command } from "commander";
import chalk from "chalk";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getAllAdapters, listCommands } from "../registry.js";
import { VERSION } from "../constants.js";

export function registerAgentsCommand(program: Command): void {
  const agents = program
    .command("agents")
    .description("AGENTS.md generation and management");

  agents
    .command("generate")
    .description("Auto-generate AGENTS.md from loaded adapters")
    .option("--output <path>", "output file path", "AGENTS.md")
    .action((opts: { output: string }) => {
      const adapters = getAllAdapters();
      const commands = listCommands();

      if (adapters.length === 0) {
        console.error(chalk.red("No adapters loaded"));
        process.exit(1);
      }

      const siteCount = adapters.length;
      const cmdCount = commands.length;
      const date = new Date().toISOString().split("T")[0];

      // Group adapters by category
      const categories = new Map<string, typeof adapters>();
      for (const adapter of adapters) {
        const cat = adapter.category ?? "Uncategorized";
        const group = categories.get(cat);
        if (group) {
          group.push(adapter);
        } else {
          categories.set(cat, [adapter]);
        }
      }

      // Build AGENTS.md content
      const lines: string[] = [];

      lines.push(
        `<!-- unicli v${VERSION} | ${siteCount} sites | ${cmdCount} commands -->`,
      );
      lines.push("# AGENTS.md — Uni-CLI Capability Discovery");
      lines.push("");
      lines.push("> Auto-generated. Do not edit manually.");
      lines.push("> Regenerate with: `unicli agents generate`");
      lines.push("");

      // Sites by Category
      lines.push("## Sites by Category");
      lines.push("");

      const sortedCategories = Array.from(categories.entries()).sort(
        ([a], [b]) => a.localeCompare(b),
      );

      for (const [category, adaptersInCat] of sortedCategories) {
        lines.push(`### ${category}`);
        lines.push("");
        lines.push("| Site | Commands | Auth | Description |");
        lines.push("|------|----------|------|-------------|");

        const sorted = adaptersInCat.sort((a, b) =>
          a.name.localeCompare(b.name),
        );

        for (const adapter of sorted) {
          const cmdNames = Object.keys(adapter.commands).sort().join(", ");
          const auth = adapter.strategy ?? "public";
          const desc = adapter.description ?? "";
          lines.push(`| ${adapter.name} | ${cmdNames} | ${auth} | ${desc} |`);
        }

        lines.push("");
      }

      // All Commands
      lines.push("## All Commands");
      lines.push("");
      lines.push("| Site | Command | Description | Auth |");
      lines.push("|------|---------|-------------|------|");

      for (const cmd of commands) {
        const auth = cmd.auth ? "yes" : "no";
        lines.push(
          `| ${cmd.site} | ${cmd.command} | ${cmd.description} | ${auth} |`,
        );
      }

      lines.push("");
      lines.push("---");
      lines.push(`<!-- Generated by Uni-CLI v${VERSION} on ${date} -->`);
      lines.push("");

      const content = lines.join("\n");
      const outPath = resolve(opts.output);

      writeFileSync(outPath, content, "utf-8");

      // Summary to stderr so it doesn't pollute piped output
      console.error(
        chalk.green(
          `Generated ${outPath} (${siteCount} sites, ${cmdCount} commands)`,
        ),
      );
    });
}
