/**
 * Release script — single source of truth propagation.
 *
 * Reads version from package.json and updates ALL documentation references.
 * Run after `npm version X.Y.Z` to propagate the new version everywhere.
 *
 * Usage: npx tsx scripts/release.ts --codename "Program · Astronaut" [--dry-run]
 *        RELEASE_CODENAME="Program · Astronaut" npx tsx scripts/release.ts
 *
 * What it updates:
 * - contributing/COPY.md: Current version line
 * - README.md / README.zh-CN.md: Footer version + codename
 * - AGENTS.md: command-contract version footer
 * - CHANGELOG.md: Insert new version heading (content added manually)
 * - docs/ROADMAP.md: Current version line
 *
 * What it does NOT update (handled elsewhere):
 * - README.md / AGENTS.md / docs/ROADMAP.md / docs/zh/ROADMAP.md site/command/pipeline/test counts
 *   → auto-regenerated by scripts/build-readme.ts via `<!-- STATS:key -->` markers.
 * - CLAUDE.md → .gitignored, author-local only, never shipped.
 *
 * What it does NOT update (read from package.json at runtime):
 * - src/cli.ts — imports VERSION from constants.ts
 * - src/engine/yaml-runner.ts — imports USER_AGENT from constants.ts
 * - scripts/build-manifest.js — reads package.json directly
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// --- Read source of truth ---

const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf-8"));
const version: string = pkg.version;

// Parse CLI args
const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");

function readArgValue(name: string): string | undefined {
  const idx = args.indexOf(name);
  if (idx >= 0) return args[idx + 1];
  const prefix = `${name}=`;
  return args.find((arg) => arg.startsWith(prefix))?.slice(prefix.length);
}

function failConfig(message: string): never {
  console.error(`\n✗ Release metadata error: ${message}`);
  console.error('  Use: npm run release -- --codename "Vostok · Gagarin"');
  console.error(
    '  Or:  RELEASE_CODENAME="Vostok · Gagarin" npm version VERSION --no-git-tag-version',
  );
  process.exit(78);
}

function validateCodename(label: string): string | undefined {
  if (label.length === 0) return "missing required --codename";
  if (/\b(?:tbd|todo|unreleased|next)\b/i.test(label)) {
    return "codename must be final; placeholders like TBD/Unreleased are blocked";
  }
  if (!/^\S.+\s·\s\S.+$/.test(label)) {
    return 'codename must use the exact "Program · Astronaut" shape';
  }
  return undefined;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const codename = (
  readArgValue("--codename") ??
  process.env.RELEASE_CODENAME ??
  ""
).trim();
const codenameError = validateCodename(codename);
if (codenameError) failConfig(codenameError);

// Read manifest for site/command counts
const manifestPath = join(ROOT, "dist", "manifest.json");
let siteCount = "?";
let cmdCount = "?";
if (existsSync(manifestPath)) {
  const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
  const sites = Object.keys(manifest.sites || {});
  siteCount = String(sites.length);
  cmdCount = String(
    sites.reduce(
      (sum: number, s: string) =>
        sum + (manifest.sites[s]?.commands?.length || 0),
      0,
    ),
  );
}

// --- Replacement rules ---

interface Rule {
  file: string;
  pattern: RegExp;
  replacement: string;
  description: string;
}

// Patterns removed in v0.213.1 patch pass (previously silently SKIP'd every release):
//   - CLAUDE.md "- Version: ..."                → file is .gitignored, never shipped.
//   - AGENTS.md "## Available Sites (X)"        → header no longer exists.
//   - AGENTS.md "N sites, M commands."          → counts live in STATS markers.
//   - README.md "N_Sites-M_Commands" badge URL  → badge removed; counts via STATS.
// Site/command/pipeline/test counts in README.md, AGENTS.md, docs/ROADMAP.md,
// docs/zh/ROADMAP.md, and contributing/COPY.md are owned by
// scripts/build-readme.ts which rewrites every
// `<!-- STATS:key -->...<!-- /STATS -->` block from stats.json each `npm run build`.

const rules: Rule[] = [
  {
    file: "contributing/COPY.md",
    pattern: /^> Current version: v[\d.]+(?:\s+—\s+[^.]+)?\./m,
    replacement: `> Current version: v${version} — ${codename}.`,
    description: "COPY.md current version",
  },
  {
    file: "docs/ROADMAP.md",
    pattern: /^> Current: v[\d.]+(?:\s+—\s+[^.]+)?\./m,
    replacement: `> Current: v${version} — ${codename}.`,
    description: "ROADMAP.md current version",
  },
  {
    file: "README.md",
    pattern: /<sub>v?[\d.]+(?:\s+—\s+[^<]+)?<\/sub>/,
    replacement: `<sub>v${version} — ${codename}</sub>`,
    description: "README.md footer codename",
  },
  {
    file: "README.zh-CN.md",
    pattern: /<sub>v?[\d.]+(?:\s+—\s+[^<]+)?<\/sub>/,
    replacement: `<sub>v${version} — ${codename}</sub>`,
    description: "README.zh-CN.md footer codename",
  },
  {
    file: "AGENTS.md",
    pattern: /^## Version\n\n[\d.]+(?:\s+—\s+[^\n]+)?/m,
    replacement: `## Version\n\n${version} — ${codename}`,
    description: "AGENTS.md version",
  },
];

// --- Apply rules ---

console.log(`\n📦 Uni-CLI Release Propagation`);
console.log(`   Version: ${version}`);
console.log(`   Sites: ${siteCount} | Commands: ${cmdCount}`);
console.log(`   Codename: ${codename}`);
if (dryRun) console.log(`   Mode: DRY RUN (no writes)\n`);
else console.log();

let updated = 0;
let failed = 0;

for (const rule of rules) {
  const filePath = join(ROOT, rule.file);
  if (!existsSync(filePath)) {
    console.log(`   ✗ FAIL ${rule.file} — file not found`);
    failed++;
    continue;
  }

  const content = readFileSync(filePath, "utf-8");
  if (!rule.pattern.test(content)) {
    console.log(`   ✗ FAIL ${rule.description} — pattern not found`);
    failed++;
    continue;
  }

  const newContent = content.replace(rule.pattern, rule.replacement);
  if (newContent === content) {
    console.log(`   ✓ ${rule.description} — already up to date`);
    continue;
  }

  if (!dryRun) {
    writeFileSync(filePath, newContent);
  }
  console.log(`   ${dryRun ? "→" : "✓"} ${rule.description}`);
  updated++;
}

// --- CHANGELOG.md: insert version heading if missing ---

const changelogPath = join(ROOT, "CHANGELOG.md");
if (existsSync(changelogPath)) {
  const changelog = readFileSync(changelogPath, "utf-8");
  const escapedVersion = escapeRegExp(version);
  const versionHeadingPattern = new RegExp(
    `^## (?:\\[${escapedVersion}\\]|${escapedVersion}|@zenalexa/unicli@${escapedVersion})(?:\\s+—.*)?$`,
    "m",
  );
  const today = new Date().toISOString().slice(0, 10);
  const newHeading = `## [${version}] — ${today} — ${codename}`;

  if (versionHeadingPattern.test(changelog)) {
    const newChangelog = changelog.replace(versionHeadingPattern, newHeading);
    if (newChangelog === changelog) {
      console.log(
        `   ✓ CHANGELOG.md — heading for ${version} already up to date`,
      );
    } else {
      if (!dryRun) {
        writeFileSync(changelogPath, newChangelog);
      }
      console.log(
        `   ${dryRun ? "→" : "✓"} CHANGELOG.md — updated heading for v${version}`,
      );
      updated++;
    }
  } else {
    const newBlock = `${newHeading}\n\n### Added\n\n### Changed\n\n### Fixed\n\n`;
    // Insert after the first line that starts with "# " (the main title block)
    const insertIdx = changelog.indexOf("\n\n## ");
    if (insertIdx >= 0) {
      const before = changelog.slice(0, insertIdx);
      const after = changelog.slice(insertIdx);
      const newChangelog = `${before}\n\n${newBlock}${after.slice(2)}`;
      if (!dryRun) {
        writeFileSync(changelogPath, newChangelog);
      }
      console.log(
        `   ${dryRun ? "→" : "✓"} CHANGELOG.md — inserted heading for v${version}`,
      );
      updated++;
    } else {
      console.log(`   ✗ FAIL CHANGELOG.md — could not find insertion point`);
      failed++;
    }
  }
} else {
  console.log(`   ✗ FAIL CHANGELOG.md — file not found`);
  failed++;
}

console.log(
  `\n   ${updated} updated, ${failed} failed${dryRun ? " (dry run)" : ""}`,
);

if (failed > 0) {
  process.exit(1);
}

if (!dryRun && updated > 0) {
  console.log(`\n   Next steps:`);
  console.log(`   1. Review changes: git diff`);
  console.log(
    `   2. Commit: git commit -am "release: v${version} — ${codename}"`,
  );
  console.log(`   3. Push: git push origin main`);
}
